version: '3.8'

services:

  bot:
    build: .
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
    secrets:
      - source: botconfig
        target: /usr/src/app/config.json
    depends_on:
      - redis

  redis:
    image: redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - datavolume:/data

volumes:
  datavolume:

secrets:
  botconfig:
    file: ./config.json