name: Code formatting
on:
  push:
    branches: [master]
    paths:
      - "**.js"
  pull_request:
    branches: [master]
    paths:
      - "**.js"

jobs:
  check-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check code formatting
        run: |
          npm ci
          npm run check-formatting
