name: Docker build
on:
  push:
    branches: [master]
    paths:
      - "**"
      - "!**.md"

jobs:
  push_to_registry:
    name: Push Docker image to registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: radiantly
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: radiantly/lcb
          tags: latest
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: radiantly/live-countdown-bot/lcb
          tags: latest
          tag_with_ref: true
  deploy_to_server:
    name: Deploy to Docker Swarm
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          docker service rm app_bot || true
          docker secret rm botconfig || true
          printf '${{ secrets.BOT_CONFIG }}' | docker secret create botconfig -
          docker stack deploy -c docker-stack.yml --with-registry-auth --prune app
        env:
          DOCKER_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
