name: Publish Docker image
on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: radiantly/live-countdown-bot/lcb
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
