name: Check formatting
on:
  push:
  pull_request:

jobs:
  check:
    name: Check code formatting and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Check formatting
        run: pnpm run check-formatting
